/**
 * The json schema for the releases.json that will be generated / changed by the CLI.
 */
export interface IReleasesJson {
  /**
   * The current version of the ad tag.
   */
  readonly currentVersion: number;

  /**
   * The name of the file for the current version.
   */
  readonly currentFilename: string;

  /**
   * The name of the es5 file for the current version, if any.
   */
  readonly currentFilenameEs5?: string;

  /**
   * The name of the publisher. Needed to create a unique git tag.
   */
  readonly publisherName: string;

  /**
   * All versions that were generated by the CLI.
   */
  readonly versions: IAdTagRelease[];
}

/**
 * Type definition for a release of the ad tag.
 */
export interface IAdTagRelease {
  /**
   * The version of this ad tag release.
   */
  readonly version: number;

  /**
   * The name of the file for this version.
   */
  readonly filename: string;

  /**
   * The name of the es5 file for this version, if any.
   */
  readonly filenameEs5?: string;

  /**
   * The changes for the version of this ad tag.
   */
  readonly changelog: string[];

  /**
   * The date when this version was released.
   */
  readonly createdAt?: string;
}
