/**
 * The json schema for the releases.json that will be generated / changed by the CLI.
 */
export interface IReleasesJson {
  /**
   * The current version of the ad tag.
   */
  readonly currentVersion: number;

  /**
   * All versions that were generated by the CLI.
   */
  readonly versions: IAdTagRelease[];
}

/**
 * Type definition for a release of the ad tag.
 */
export interface IAdTagRelease {
  /**
   * The version of this ad tag release.
   */
  readonly version: number;

  /**
   * The changes for the version of this ad tag.
   */
  readonly changelog: string[];
}
