import { MoliRuntime } from 'ad-tag/types/moliRuntime';
import { GoogleAdManagerKeyValueMap, modules } from 'ad-tag/types/moliConfig';
import MoliLogger = MoliRuntime.MoliLogger;
import AdexKeyValueMap = modules.adex.AdexKeyValueMap;
import MappingDefinitionToAdexMap = modules.adex.MappingDefinitionToAdexMap;
import MappingDefinitionToAdexString = modules.adex.MappingDefinitionToAdexString;
import MappingDefinitionToAdexNumber = modules.adex.MappingDefinitionToAdexNumber;
import AdexKeyValuePair = modules.adex.AdexKeyValuePair;
import MappingDefinitionToAdexList = modules.adex.MappingDefinitionToAdexList;
import AdexList = modules.adex.AdexList;
export declare const toAdexMapType: (keyValueMap: GoogleAdManagerKeyValueMap, mappingDefinition: MappingDefinitionToAdexMap, logger: MoliLogger) => AdexKeyValueMap | undefined;
export declare const toAdexStringOrNumberType: (keyValueMap: GoogleAdManagerKeyValueMap, mappingDefinition: MappingDefinitionToAdexString | MappingDefinitionToAdexNumber, logger: MoliLogger) => AdexKeyValuePair | undefined;
export declare const toAdexListType: (keyValueMap: GoogleAdManagerKeyValueMap, mappingDefinition: MappingDefinitionToAdexList, logger: MoliLogger) => AdexList | undefined;
