import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'home/index',
    {
      type: 'category',
      label: 'Getting started',
      items: [
        'getting-started/quick-start',
        'getting-started/adtag-build',
        'getting-started/ad-slot-configuration',
        'getting-started/glossary'
      ],
      collapsed: false
    },
    {
      type: 'category',
      label: 'Configuration',
      items: [
        'features/size-config',
        'features/prebid',
        'features/tam',
        'features/consent',
        'features/targeting',
        'features/labels',
        'features/buckets',
        'features/single-page-app',
        'features/debugging',
        'features/logger',
        'features/environments',
        'features/passback',
        'features/hooks',
        'features/ad-unit-path-variables',
        'features/events'
      ],
      collapsed: false
    },
    // adds a modules link in the /docs sidebar
    {
      type: 'category',
      label: 'Modules',
      items: [
        {
          type: 'autogenerated',
          dirName: 'modules'
        }
      ],
      collapsed: true
    },
    'home/architecture',
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/getting-started',
        'guides/single-page-applications',
        'guides/performance-optimization',
        'guides/troubleshooting',
        'guides/logging',
        'guides/styleguide'
      ],
      collapsed: false
    }
  ],
  // generates the sidebar
  API: [
    {
      type: 'autogenerated',
      dirName: 'api'
    }
  ],
  Modules: [
    {
      type: 'autogenerated',
      dirName: 'modules'
    }
  ]
};

export default sidebars;
