module.exports = {
  docs: [
    'index',
    {
      type: 'category',
      label: 'Getting started',
      items: [
        'getting-started/quick-start',
        'getting-started/adtag-build',
        'getting-started/ad-slot-configuration',
        'getting-started/glossary'
      ],
      collapsed: false
    },
    {
      type: 'category',
      label: 'Configuration',
      items: [
        'features/size-config',
        'features/prebid',
        'features/tam',
        'features/consent',
        'features/targeting',
        'features/labels',
        'features/buckets',
        'features/debugging',
        'features/logger',
        'features/environments',
        'features/reporting',
        'features/passback'
      ],
      collapsed: false
    },
    // adds a modules link in the /docs sidebar
    {
      type: 'category',
      label: 'Modules',
      items: [
        {
          type: 'autogenerated',
          dirName: 'modules/modules'
        }
      ],
      collapsed: true
    },
    'architecture',
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/conditional-ad-slots',
        'guides/immutable-ad-tags',
        'guides/logging',
        'guides/styleguide'
      ],
      collapsed: false
    }
  ],
  // generates the sidebar
  API: [
    {
      type: 'autogenerated',
      dirName: 'api'
    }
  ],
  Modules: [
    {
      type: 'autogenerated',
      dirName: 'modules'
    }
  ]
};
