name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: [
            ad-tag,
            module-moli-ad-reload,
            module-the-adex-dmp,
            module-blocklist-url,
            module-confiant,
            module-emetriq,
            module-generic-skin,
            module-identitylink,
            module-moli-lazy-load,
            module-prebid-first-party-data,
            module-sticky-footer-ads,
            module-sticky-header-ads,
            module-yield-optimization,
            module-zeotap,
            moli-debugger,
            moli-release
        ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Node Private Registry
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
          always-auth: true
          node-version: 18
          registry-url: https://npm.pkg.github.com
          scope: '@highfivve'

      - name: Install dependencies
        run: yarn && yarn setup
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build ${{ matrix.package }}
        run: yarn workspace @highfivve/${{ matrix.package }} make:nodemodule

      - name: Validate ${{ matrix.package }}
        run: yarn workspace @highfivve/${{ matrix.package }} validate:github
