name: Build examples

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        working_directory:
          - esbuild
          - rollup

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Node Private Registry
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          always-auth: true
          node-version: 20
          registry-url: https://npm.pkg.github.com
          scope: '@highfivve'

      - name: setup
        run: npm run setup
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build ad tag lib
        run: npm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies ( ${{ matrix.version }} )
        run: npm ci
        working-directory: examples/${{ matrix.working_directory }}
        env:
         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build ${{ matrix.version }}
        working-directory: examples/${{ matrix.working_directory }}
        run: npm run build
        env:
          NODE_ENV: production
