name: Build and Test

on:
  push:
    branches: [ GD-1363-github-npm-registry ]
  pull_request:
    branches: [ GD-1363-github-npm-registry ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module: [
            ad-tag,
            module-blocklist-url
        ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Setup Node Private Registry
        uses: actions/setup.node@v1
        with:
          always-auth: true
          node-version: 12.x
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@highfivve'

      # TODO cache dependencies
      # @see https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows

      - name: Install dependencies
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Validate
        run: yarn workspace @highfivve/${{ matrix.module }} validate:github
