name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module: [
            ad-tag,
            module-blocklist-url,
            module-confiant,
            module-cmp-sourcepoint,
            module-generic-skin,
            module-justpremium-skin,
            module-prebid-google-analytics,
            module-sovrn-ad-reload,
            moli-debugger,
            moli-release
        ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Setup Node Private Registry
        uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: 12.x
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@highfivve'

      # cache dependencies
      # @see https://github.com/actions/cache/blob/main/examples.md#node---yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build
        run: yarn lerna run make:nodemodule

      - name: Validate
        run: yarn workspace @highfivve/${{ matrix.module }} validate:github
