name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    # TODO probably add a strategy.matrix as well to test all examples
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Node Private Registry
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          always-auth: true
          node-version: 20
          registry-url: https://npm.pkg.github.com
          scope: '@highfivve'

      - name: Install dependencies
        run: npm install
        working-directory: examples/esbuild
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build
        working-directory: examples/esbuild
        run: npm run build
