name: Build and Test

on:
  push:
    branches: [ GD-1363-github-npm-registry ]
  pull_request:
    branches: [ GD-1363-github-npm-registry ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module: [
            ad-tag,
            module-blocklist-url,
            module-confiant,
            module-cmp-sourcepoint,
            module-generic-skin,
            module-justpremium-skin,
            module-prebid-google-analytics,
            module-sovrn-ad-reload,
            moli-debugger
        ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      # TODO cache dependencies
      # @see https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows

      - name: Install dependencies
        run: yarn

      - name: Validate
        run: yarn workspace @highfivve/${{ matrix.module }} validate:github
