name: Github Pages Deployment

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Get release version from tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      # Setup node
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      ## type declarations need to be present for docs to work properly
      - name: setup project
        run: npm run setup

      # Build website
      - name: build website
        working-directory: ./website
        run: |
          npm install
          npm build

      - name: create versioned asset directory
        run: |
          mkdir -p website/build/assets/js/${{ env.RELEASE_VERSION }}

      # Build prebuilt ad-tag
      - name: build adtag
        working-directory: ./prebuilt/ad-tag
        run: |
          npm install
          npm build
          cp dist/* ../../website/build/assets/js/
          cp dist/* ../../website/build/assets/js/${{ env.RELEASE_VERSION }}/

      # Build ad tag console
      - name: build ad tag console / debugger
        working-directory: ./moli-debugger
        run: |
          npm install
          npm build
          cp lib/* ../website/build/assets/js/
          cp lib/* ../website/build/assets/js/${{ env.RELEASE_VERSION }}/

      # Deploy website
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: website/build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
