name: Check JSON Schema

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Schema Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Node Private Registry
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          always-auth: true
          node-version: 20
          registry-url: https://npm.pkg.github.com
          scope: '@highfivve'

      - name: Install dependencies
        run: npm ci && npm run setup
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Generate JSON Schema
        run: npm run schema

      - name: Verify JSON Schema unchanged
        uses: tj-actions/verify-changed-files@v20
        id: verify-changed-files
        with:
          fail-if-changed: true
          fail-message: 'Schema files have changed. Please run `npm run schema` and commit the changes.'
          files: |
            schema.json
            **/*.json
